//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1.
// 
#pragma warning disable 1591

namespace WebPfizer.LMS.eCard.WSeCardPfizerVen {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsLMSeCardCRMSoap", Namespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/")]
    public partial class WsLMSeCardCRM : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TarjetasRegistradasOperationCompleted;
        
        private System.Threading.SendOrPostCallback TarjetaClienteConfirmacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback TarjetasRegistradasDemoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransaccionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransaccionesConfirmacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransaccionesDemoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaestroCadenasOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaestroCadenasDemoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaestroTarjetasOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaestroTarjetasDemoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaestroSucursalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaestroSucursalesDemoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaestroProductosOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaestroProductosDemoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaestroProductosPresentacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsLMSeCardCRM() {
            this.Url = global::WebPfizer.LMS.eCard.Properties.Settings.Default.WebPfizer_LMS_eCard_WSeCardPfizerVen_WsLMSeCardCRM;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TarjetasRegistradasCompletedEventHandler TarjetasRegistradasCompleted;
        
        /// <remarks/>
        public event TarjetaClienteConfirmacionCompletedEventHandler TarjetaClienteConfirmacionCompleted;
        
        /// <remarks/>
        public event TarjetasRegistradasDemoCompletedEventHandler TarjetasRegistradasDemoCompleted;
        
        /// <remarks/>
        public event TransaccionesCompletedEventHandler TransaccionesCompleted;
        
        /// <remarks/>
        public event TransaccionesConfirmacionCompletedEventHandler TransaccionesConfirmacionCompleted;
        
        /// <remarks/>
        public event TransaccionesDemoCompletedEventHandler TransaccionesDemoCompleted;
        
        /// <remarks/>
        public event MaestroCadenasCompletedEventHandler MaestroCadenasCompleted;
        
        /// <remarks/>
        public event MaestroCadenasDemoCompletedEventHandler MaestroCadenasDemoCompleted;
        
        /// <remarks/>
        public event MaestroTarjetasCompletedEventHandler MaestroTarjetasCompleted;
        
        /// <remarks/>
        public event MaestroTarjetasDemoCompletedEventHandler MaestroTarjetasDemoCompleted;
        
        /// <remarks/>
        public event MaestroSucursalesCompletedEventHandler MaestroSucursalesCompleted;
        
        /// <remarks/>
        public event MaestroSucursalesDemoCompletedEventHandler MaestroSucursalesDemoCompleted;
        
        /// <remarks/>
        public event MaestroProductosCompletedEventHandler MaestroProductosCompleted;
        
        /// <remarks/>
        public event MaestroProductosDemoCompletedEventHandler MaestroProductosDemoCompleted;
        
        /// <remarks/>
        public event MaestroProductosPresentacionCompletedEventHandler MaestroProductosPresentacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/TarjetasRegistradas", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TarjetaCliente[] TarjetasRegistradas(string programaID, string key, int tipoExtraccion, string fecha, string strUsuario) {
            object[] results = this.Invoke("TarjetasRegistradas", new object[] {
                        programaID,
                        key,
                        tipoExtraccion,
                        fecha,
                        strUsuario});
            return ((TarjetaCliente[])(results[0]));
        }
        
        /// <remarks/>
        public void TarjetasRegistradasAsync(string programaID, string key, int tipoExtraccion, string fecha, string strUsuario) {
            this.TarjetasRegistradasAsync(programaID, key, tipoExtraccion, fecha, strUsuario, null);
        }
        
        /// <remarks/>
        public void TarjetasRegistradasAsync(string programaID, string key, int tipoExtraccion, string fecha, string strUsuario, object userState) {
            if ((this.TarjetasRegistradasOperationCompleted == null)) {
                this.TarjetasRegistradasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTarjetasRegistradasOperationCompleted);
            }
            this.InvokeAsync("TarjetasRegistradas", new object[] {
                        programaID,
                        key,
                        tipoExtraccion,
                        fecha,
                        strUsuario}, this.TarjetasRegistradasOperationCompleted, userState);
        }
        
        private void OnTarjetasRegistradasOperationCompleted(object arg) {
            if ((this.TarjetasRegistradasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TarjetasRegistradasCompleted(this, new TarjetasRegistradasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/TarjetaClienteConfirmacion", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TarjetaClienteConfirmacion(string programaID, string key, int paqueteEntrega, string listatarjetacliente, int estatus) {
            object[] results = this.Invoke("TarjetaClienteConfirmacion", new object[] {
                        programaID,
                        key,
                        paqueteEntrega,
                        listatarjetacliente,
                        estatus});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TarjetaClienteConfirmacionAsync(string programaID, string key, int paqueteEntrega, string listatarjetacliente, int estatus) {
            this.TarjetaClienteConfirmacionAsync(programaID, key, paqueteEntrega, listatarjetacliente, estatus, null);
        }
        
        /// <remarks/>
        public void TarjetaClienteConfirmacionAsync(string programaID, string key, int paqueteEntrega, string listatarjetacliente, int estatus, object userState) {
            if ((this.TarjetaClienteConfirmacionOperationCompleted == null)) {
                this.TarjetaClienteConfirmacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTarjetaClienteConfirmacionOperationCompleted);
            }
            this.InvokeAsync("TarjetaClienteConfirmacion", new object[] {
                        programaID,
                        key,
                        paqueteEntrega,
                        listatarjetacliente,
                        estatus}, this.TarjetaClienteConfirmacionOperationCompleted, userState);
        }
        
        private void OnTarjetaClienteConfirmacionOperationCompleted(object arg) {
            if ((this.TarjetaClienteConfirmacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TarjetaClienteConfirmacionCompleted(this, new TarjetaClienteConfirmacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/TarjetasRegistradasDemo", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TarjetaCliente[] TarjetasRegistradasDemo() {
            object[] results = this.Invoke("TarjetasRegistradasDemo", new object[0]);
            return ((TarjetaCliente[])(results[0]));
        }
        
        /// <remarks/>
        public void TarjetasRegistradasDemoAsync() {
            this.TarjetasRegistradasDemoAsync(null);
        }
        
        /// <remarks/>
        public void TarjetasRegistradasDemoAsync(object userState) {
            if ((this.TarjetasRegistradasDemoOperationCompleted == null)) {
                this.TarjetasRegistradasDemoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTarjetasRegistradasDemoOperationCompleted);
            }
            this.InvokeAsync("TarjetasRegistradasDemo", new object[0], this.TarjetasRegistradasDemoOperationCompleted, userState);
        }
        
        private void OnTarjetasRegistradasDemoOperationCompleted(object arg) {
            if ((this.TarjetasRegistradasDemoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TarjetasRegistradasDemoCompleted(this, new TarjetasRegistradasDemoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/Transacciones", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transacciones[] Transacciones(string programaID, string key, int tipoExtraccion, string fecha, string strUsuario) {
            object[] results = this.Invoke("Transacciones", new object[] {
                        programaID,
                        key,
                        tipoExtraccion,
                        fecha,
                        strUsuario});
            return ((Transacciones[])(results[0]));
        }
        
        /// <remarks/>
        public void TransaccionesAsync(string programaID, string key, int tipoExtraccion, string fecha, string strUsuario) {
            this.TransaccionesAsync(programaID, key, tipoExtraccion, fecha, strUsuario, null);
        }
        
        /// <remarks/>
        public void TransaccionesAsync(string programaID, string key, int tipoExtraccion, string fecha, string strUsuario, object userState) {
            if ((this.TransaccionesOperationCompleted == null)) {
                this.TransaccionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransaccionesOperationCompleted);
            }
            this.InvokeAsync("Transacciones", new object[] {
                        programaID,
                        key,
                        tipoExtraccion,
                        fecha,
                        strUsuario}, this.TransaccionesOperationCompleted, userState);
        }
        
        private void OnTransaccionesOperationCompleted(object arg) {
            if ((this.TransaccionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransaccionesCompleted(this, new TransaccionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/TransaccionesConfirmacion", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TransaccionesConfirmacion(string programaID, string key, int paqueteEntrega, string listatransacciones, int estatus) {
            object[] results = this.Invoke("TransaccionesConfirmacion", new object[] {
                        programaID,
                        key,
                        paqueteEntrega,
                        listatransacciones,
                        estatus});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TransaccionesConfirmacionAsync(string programaID, string key, int paqueteEntrega, string listatransacciones, int estatus) {
            this.TransaccionesConfirmacionAsync(programaID, key, paqueteEntrega, listatransacciones, estatus, null);
        }
        
        /// <remarks/>
        public void TransaccionesConfirmacionAsync(string programaID, string key, int paqueteEntrega, string listatransacciones, int estatus, object userState) {
            if ((this.TransaccionesConfirmacionOperationCompleted == null)) {
                this.TransaccionesConfirmacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransaccionesConfirmacionOperationCompleted);
            }
            this.InvokeAsync("TransaccionesConfirmacion", new object[] {
                        programaID,
                        key,
                        paqueteEntrega,
                        listatransacciones,
                        estatus}, this.TransaccionesConfirmacionOperationCompleted, userState);
        }
        
        private void OnTransaccionesConfirmacionOperationCompleted(object arg) {
            if ((this.TransaccionesConfirmacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransaccionesConfirmacionCompleted(this, new TransaccionesConfirmacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/TransaccionesDemo", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Transacciones[] TransaccionesDemo() {
            object[] results = this.Invoke("TransaccionesDemo", new object[0]);
            return ((Transacciones[])(results[0]));
        }
        
        /// <remarks/>
        public void TransaccionesDemoAsync() {
            this.TransaccionesDemoAsync(null);
        }
        
        /// <remarks/>
        public void TransaccionesDemoAsync(object userState) {
            if ((this.TransaccionesDemoOperationCompleted == null)) {
                this.TransaccionesDemoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransaccionesDemoOperationCompleted);
            }
            this.InvokeAsync("TransaccionesDemo", new object[0], this.TransaccionesDemoOperationCompleted, userState);
        }
        
        private void OnTransaccionesDemoOperationCompleted(object arg) {
            if ((this.TransaccionesDemoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransaccionesDemoCompleted(this, new TransaccionesDemoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/MaestroCadenas", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MaestroCadenas(string programaID, string key, Cadenas[] listaCadenas, string strUsuario) {
            object[] results = this.Invoke("MaestroCadenas", new object[] {
                        programaID,
                        key,
                        listaCadenas,
                        strUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MaestroCadenasAsync(string programaID, string key, Cadenas[] listaCadenas, string strUsuario) {
            this.MaestroCadenasAsync(programaID, key, listaCadenas, strUsuario, null);
        }
        
        /// <remarks/>
        public void MaestroCadenasAsync(string programaID, string key, Cadenas[] listaCadenas, string strUsuario, object userState) {
            if ((this.MaestroCadenasOperationCompleted == null)) {
                this.MaestroCadenasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaestroCadenasOperationCompleted);
            }
            this.InvokeAsync("MaestroCadenas", new object[] {
                        programaID,
                        key,
                        listaCadenas,
                        strUsuario}, this.MaestroCadenasOperationCompleted, userState);
        }
        
        private void OnMaestroCadenasOperationCompleted(object arg) {
            if ((this.MaestroCadenasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaestroCadenasCompleted(this, new MaestroCadenasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/MaestroCadenasDemo", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MaestroCadenasDemo() {
            object[] results = this.Invoke("MaestroCadenasDemo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MaestroCadenasDemoAsync() {
            this.MaestroCadenasDemoAsync(null);
        }
        
        /// <remarks/>
        public void MaestroCadenasDemoAsync(object userState) {
            if ((this.MaestroCadenasDemoOperationCompleted == null)) {
                this.MaestroCadenasDemoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaestroCadenasDemoOperationCompleted);
            }
            this.InvokeAsync("MaestroCadenasDemo", new object[0], this.MaestroCadenasDemoOperationCompleted, userState);
        }
        
        private void OnMaestroCadenasDemoOperationCompleted(object arg) {
            if ((this.MaestroCadenasDemoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaestroCadenasDemoCompleted(this, new MaestroCadenasDemoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/MaestroTarjetas", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MaestroTarjetas(string programaID, string key, Tarjetas[] listaTarjetas, string strUsuario) {
            object[] results = this.Invoke("MaestroTarjetas", new object[] {
                        programaID,
                        key,
                        listaTarjetas,
                        strUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MaestroTarjetasAsync(string programaID, string key, Tarjetas[] listaTarjetas, string strUsuario) {
            this.MaestroTarjetasAsync(programaID, key, listaTarjetas, strUsuario, null);
        }
        
        /// <remarks/>
        public void MaestroTarjetasAsync(string programaID, string key, Tarjetas[] listaTarjetas, string strUsuario, object userState) {
            if ((this.MaestroTarjetasOperationCompleted == null)) {
                this.MaestroTarjetasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaestroTarjetasOperationCompleted);
            }
            this.InvokeAsync("MaestroTarjetas", new object[] {
                        programaID,
                        key,
                        listaTarjetas,
                        strUsuario}, this.MaestroTarjetasOperationCompleted, userState);
        }
        
        private void OnMaestroTarjetasOperationCompleted(object arg) {
            if ((this.MaestroTarjetasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaestroTarjetasCompleted(this, new MaestroTarjetasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/MaestroTarjetasDemo", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MaestroTarjetasDemo() {
            object[] results = this.Invoke("MaestroTarjetasDemo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MaestroTarjetasDemoAsync() {
            this.MaestroTarjetasDemoAsync(null);
        }
        
        /// <remarks/>
        public void MaestroTarjetasDemoAsync(object userState) {
            if ((this.MaestroTarjetasDemoOperationCompleted == null)) {
                this.MaestroTarjetasDemoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaestroTarjetasDemoOperationCompleted);
            }
            this.InvokeAsync("MaestroTarjetasDemo", new object[0], this.MaestroTarjetasDemoOperationCompleted, userState);
        }
        
        private void OnMaestroTarjetasDemoOperationCompleted(object arg) {
            if ((this.MaestroTarjetasDemoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaestroTarjetasDemoCompleted(this, new MaestroTarjetasDemoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/MaestroSucursales", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MaestroSucursales(string programaID, string key, Sucursales[] listaSucursales, string strUsuario) {
            object[] results = this.Invoke("MaestroSucursales", new object[] {
                        programaID,
                        key,
                        listaSucursales,
                        strUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MaestroSucursalesAsync(string programaID, string key, Sucursales[] listaSucursales, string strUsuario) {
            this.MaestroSucursalesAsync(programaID, key, listaSucursales, strUsuario, null);
        }
        
        /// <remarks/>
        public void MaestroSucursalesAsync(string programaID, string key, Sucursales[] listaSucursales, string strUsuario, object userState) {
            if ((this.MaestroSucursalesOperationCompleted == null)) {
                this.MaestroSucursalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaestroSucursalesOperationCompleted);
            }
            this.InvokeAsync("MaestroSucursales", new object[] {
                        programaID,
                        key,
                        listaSucursales,
                        strUsuario}, this.MaestroSucursalesOperationCompleted, userState);
        }
        
        private void OnMaestroSucursalesOperationCompleted(object arg) {
            if ((this.MaestroSucursalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaestroSucursalesCompleted(this, new MaestroSucursalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/MaestroSucursalesDemo", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MaestroSucursalesDemo() {
            object[] results = this.Invoke("MaestroSucursalesDemo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MaestroSucursalesDemoAsync() {
            this.MaestroSucursalesDemoAsync(null);
        }
        
        /// <remarks/>
        public void MaestroSucursalesDemoAsync(object userState) {
            if ((this.MaestroSucursalesDemoOperationCompleted == null)) {
                this.MaestroSucursalesDemoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaestroSucursalesDemoOperationCompleted);
            }
            this.InvokeAsync("MaestroSucursalesDemo", new object[0], this.MaestroSucursalesDemoOperationCompleted, userState);
        }
        
        private void OnMaestroSucursalesDemoOperationCompleted(object arg) {
            if ((this.MaestroSucursalesDemoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaestroSucursalesDemoCompleted(this, new MaestroSucursalesDemoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/MaestroProductos", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MaestroProductos(string programaID, string key, Producto[] listaProductos, string strUsuario) {
            object[] results = this.Invoke("MaestroProductos", new object[] {
                        programaID,
                        key,
                        listaProductos,
                        strUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MaestroProductosAsync(string programaID, string key, Producto[] listaProductos, string strUsuario) {
            this.MaestroProductosAsync(programaID, key, listaProductos, strUsuario, null);
        }
        
        /// <remarks/>
        public void MaestroProductosAsync(string programaID, string key, Producto[] listaProductos, string strUsuario, object userState) {
            if ((this.MaestroProductosOperationCompleted == null)) {
                this.MaestroProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaestroProductosOperationCompleted);
            }
            this.InvokeAsync("MaestroProductos", new object[] {
                        programaID,
                        key,
                        listaProductos,
                        strUsuario}, this.MaestroProductosOperationCompleted, userState);
        }
        
        private void OnMaestroProductosOperationCompleted(object arg) {
            if ((this.MaestroProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaestroProductosCompleted(this, new MaestroProductosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/MaestroProductosDemo", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MaestroProductosDemo() {
            object[] results = this.Invoke("MaestroProductosDemo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MaestroProductosDemoAsync() {
            this.MaestroProductosDemoAsync(null);
        }
        
        /// <remarks/>
        public void MaestroProductosDemoAsync(object userState) {
            if ((this.MaestroProductosDemoOperationCompleted == null)) {
                this.MaestroProductosDemoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaestroProductosDemoOperationCompleted);
            }
            this.InvokeAsync("MaestroProductosDemo", new object[0], this.MaestroProductosDemoOperationCompleted, userState);
        }
        
        private void OnMaestroProductosDemoOperationCompleted(object arg) {
            if ((this.MaestroProductosDemoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaestroProductosDemoCompleted(this, new MaestroProductosDemoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WsLMS_eCardCRM_DynamicsVzla.com.mx/MaestroProductosPresentacion", RequestNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", ResponseNamespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MaestroProductosPresentacion(string programaID, string key, Presentacion[] listaProductosPresentacion, string strUsuario) {
            object[] results = this.Invoke("MaestroProductosPresentacion", new object[] {
                        programaID,
                        key,
                        listaProductosPresentacion,
                        strUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MaestroProductosPresentacionAsync(string programaID, string key, Presentacion[] listaProductosPresentacion, string strUsuario) {
            this.MaestroProductosPresentacionAsync(programaID, key, listaProductosPresentacion, strUsuario, null);
        }
        
        /// <remarks/>
        public void MaestroProductosPresentacionAsync(string programaID, string key, Presentacion[] listaProductosPresentacion, string strUsuario, object userState) {
            if ((this.MaestroProductosPresentacionOperationCompleted == null)) {
                this.MaestroProductosPresentacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaestroProductosPresentacionOperationCompleted);
            }
            this.InvokeAsync("MaestroProductosPresentacion", new object[] {
                        programaID,
                        key,
                        listaProductosPresentacion,
                        strUsuario}, this.MaestroProductosPresentacionOperationCompleted, userState);
        }
        
        private void OnMaestroProductosPresentacionOperationCompleted(object arg) {
            if ((this.MaestroProductosPresentacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaestroProductosPresentacionCompleted(this, new MaestroProductosPresentacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/")]
    public partial class TarjetaCliente {
        
        private string errorField;
        
        private string mensajeField;
        
        private int totalRegistrosField;
        
        private int paqueteEntregaField;
        
        private string clienteIDField;
        
        private string tarjetaIDField;
        
        private string apellidoPField;
        
        private string apellidoMField;
        
        private string nombreField;
        
        private string fechaAltaField;
        
        private string cedulaField;
        
        private string telefonoField;
        
        private string medicoField;
        
        private string iDSucursalField;
        
        private string mecanicasField;
        
        /// <comentarios/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <comentarios/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public int TotalRegistros {
            get {
                return this.totalRegistrosField;
            }
            set {
                this.totalRegistrosField = value;
            }
        }
        
        /// <comentarios/>
        public int PaqueteEntrega {
            get {
                return this.paqueteEntregaField;
            }
            set {
                this.paqueteEntregaField = value;
            }
        }
        
        /// <comentarios/>
        public string ClienteID {
            get {
                return this.clienteIDField;
            }
            set {
                this.clienteIDField = value;
            }
        }
        
        /// <comentarios/>
        public string TarjetaID {
            get {
                return this.tarjetaIDField;
            }
            set {
                this.tarjetaIDField = value;
            }
        }
        
        /// <comentarios/>
        public string ApellidoP {
            get {
                return this.apellidoPField;
            }
            set {
                this.apellidoPField = value;
            }
        }
        
        /// <comentarios/>
        public string ApellidoM {
            get {
                return this.apellidoMField;
            }
            set {
                this.apellidoMField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaAlta {
            get {
                return this.fechaAltaField;
            }
            set {
                this.fechaAltaField = value;
            }
        }
        
        /// <comentarios/>
        public string Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
            }
        }
        
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public string Medico {
            get {
                return this.medicoField;
            }
            set {
                this.medicoField = value;
            }
        }
        
        /// <comentarios/>
        public string IDSucursal {
            get {
                return this.iDSucursalField;
            }
            set {
                this.iDSucursalField = value;
            }
        }
        
        /// <comentarios/>
        public string Mecanicas {
            get {
                return this.mecanicasField;
            }
            set {
                this.mecanicasField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/")]
    public partial class Presentacion {
        
        private string presentacionStrSKUField;
        
        private string productoStrIDField;
        
        private string presentacionStrIDField;
        
        private string presentacionStrDescripcionField;
        
        private string presentacionStrSKUBeneficioField;
        
        private int presentacionIntCantidadCompraField;
        
        private int presentacionIntCantidadBeneficioField;
        
        private int presentacionIntLimiteMensualField;
        
        private int presentacionIntStatusField;
        
        /// <comentarios/>
        public string PresentacionStrSKU {
            get {
                return this.presentacionStrSKUField;
            }
            set {
                this.presentacionStrSKUField = value;
            }
        }
        
        /// <comentarios/>
        public string ProductoStrID {
            get {
                return this.productoStrIDField;
            }
            set {
                this.productoStrIDField = value;
            }
        }
        
        /// <comentarios/>
        public string PresentacionStrID {
            get {
                return this.presentacionStrIDField;
            }
            set {
                this.presentacionStrIDField = value;
            }
        }
        
        /// <comentarios/>
        public string PresentacionStrDescripcion {
            get {
                return this.presentacionStrDescripcionField;
            }
            set {
                this.presentacionStrDescripcionField = value;
            }
        }
        
        /// <comentarios/>
        public string PresentacionStrSKUBeneficio {
            get {
                return this.presentacionStrSKUBeneficioField;
            }
            set {
                this.presentacionStrSKUBeneficioField = value;
            }
        }
        
        /// <comentarios/>
        public int PresentacionIntCantidadCompra {
            get {
                return this.presentacionIntCantidadCompraField;
            }
            set {
                this.presentacionIntCantidadCompraField = value;
            }
        }
        
        /// <comentarios/>
        public int PresentacionIntCantidadBeneficio {
            get {
                return this.presentacionIntCantidadBeneficioField;
            }
            set {
                this.presentacionIntCantidadBeneficioField = value;
            }
        }
        
        /// <comentarios/>
        public int PresentacionIntLimiteMensual {
            get {
                return this.presentacionIntLimiteMensualField;
            }
            set {
                this.presentacionIntLimiteMensualField = value;
            }
        }
        
        /// <comentarios/>
        public int PresentacionIntStatus {
            get {
                return this.presentacionIntStatusField;
            }
            set {
                this.presentacionIntStatusField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/")]
    public partial class Producto {
        
        private string productoStrIDField;
        
        private string productoStrDescripcionField;
        
        private int productoIntStatusField;
        
        /// <comentarios/>
        public string ProductoStrID {
            get {
                return this.productoStrIDField;
            }
            set {
                this.productoStrIDField = value;
            }
        }
        
        /// <comentarios/>
        public string ProductoStrDescripcion {
            get {
                return this.productoStrDescripcionField;
            }
            set {
                this.productoStrDescripcionField = value;
            }
        }
        
        /// <comentarios/>
        public int ProductoIntStatus {
            get {
                return this.productoIntStatusField;
            }
            set {
                this.productoIntStatusField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/")]
    public partial class Sucursales {
        
        private int cadena_IntIDField;
        
        private string sucursal_StrIDField;
        
        private string sucursal_StrNombreField;
        
        private int sucursal_IntParticipaField;
        
        /// <comentarios/>
        public int Cadena_IntID {
            get {
                return this.cadena_IntIDField;
            }
            set {
                this.cadena_IntIDField = value;
            }
        }
        
        /// <comentarios/>
        public string Sucursal_StrID {
            get {
                return this.sucursal_StrIDField;
            }
            set {
                this.sucursal_StrIDField = value;
            }
        }
        
        /// <comentarios/>
        public string Sucursal_StrNombre {
            get {
                return this.sucursal_StrNombreField;
            }
            set {
                this.sucursal_StrNombreField = value;
            }
        }
        
        /// <comentarios/>
        public int Sucursal_IntParticipa {
            get {
                return this.sucursal_IntParticipaField;
            }
            set {
                this.sucursal_IntParticipaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/")]
    public partial class Tarjetas {
        
        private string tarjeta_StrIDField;
        
        private string tarjeta_StrMecanicasField;
        
        private int tarjeta_IntParticipaField;
        
        /// <comentarios/>
        public string Tarjeta_StrID {
            get {
                return this.tarjeta_StrIDField;
            }
            set {
                this.tarjeta_StrIDField = value;
            }
        }
        
        /// <comentarios/>
        public string Tarjeta_StrMecanicas {
            get {
                return this.tarjeta_StrMecanicasField;
            }
            set {
                this.tarjeta_StrMecanicasField = value;
            }
        }
        
        /// <comentarios/>
        public int Tarjeta_IntParticipa {
            get {
                return this.tarjeta_IntParticipaField;
            }
            set {
                this.tarjeta_IntParticipaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/")]
    public partial class Cadenas {
        
        private int cadenaIntIDField;
        
        private string cadena_strNombreField;
        
        private int cadena_intParticipaField;
        
        /// <comentarios/>
        public int CadenaIntID {
            get {
                return this.cadenaIntIDField;
            }
            set {
                this.cadenaIntIDField = value;
            }
        }
        
        /// <comentarios/>
        public string Cadena_strNombre {
            get {
                return this.cadena_strNombreField;
            }
            set {
                this.cadena_strNombreField = value;
            }
        }
        
        /// <comentarios/>
        public int Cadena_intParticipa {
            get {
                return this.cadena_intParticipaField;
            }
            set {
                this.cadena_intParticipaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WsLMS_eCardCRM_DynamicsVzla.com.mx/")]
    public partial class Transacciones {
        
        private string errorField;
        
        private string mensajeField;
        
        private int totalRegistrosField;
        
        private int registroInsercionField;
        
        private int transaccionIntIDField;
        
        private int cadenaIntIDField;
        
        private int sucursalIntIDField;
        
        private string sucursalStrIDField;
        
        private string tarjetaStrNumeroField;
        
        private string transaccionDateFechaField;
        
        private string presentacionIntSKUField;
        
        private string presentacionStrIDField;
        
        private int transaccionIntCantidadField;
        
        private string transaccionStrTipoMovField;
        
        private string transaccionStrSubTipoMovField;
        
        /// <comentarios/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <comentarios/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public int TotalRegistros {
            get {
                return this.totalRegistrosField;
            }
            set {
                this.totalRegistrosField = value;
            }
        }
        
        /// <comentarios/>
        public int RegistroInsercion {
            get {
                return this.registroInsercionField;
            }
            set {
                this.registroInsercionField = value;
            }
        }
        
        /// <comentarios/>
        public int TransaccionIntID {
            get {
                return this.transaccionIntIDField;
            }
            set {
                this.transaccionIntIDField = value;
            }
        }
        
        /// <comentarios/>
        public int CadenaIntID {
            get {
                return this.cadenaIntIDField;
            }
            set {
                this.cadenaIntIDField = value;
            }
        }
        
        /// <comentarios/>
        public int SucursalIntID {
            get {
                return this.sucursalIntIDField;
            }
            set {
                this.sucursalIntIDField = value;
            }
        }
        
        /// <comentarios/>
        public string SucursalStrID {
            get {
                return this.sucursalStrIDField;
            }
            set {
                this.sucursalStrIDField = value;
            }
        }
        
        /// <comentarios/>
        public string TarjetaStrNumero {
            get {
                return this.tarjetaStrNumeroField;
            }
            set {
                this.tarjetaStrNumeroField = value;
            }
        }
        
        /// <comentarios/>
        public string TransaccionDateFecha {
            get {
                return this.transaccionDateFechaField;
            }
            set {
                this.transaccionDateFechaField = value;
            }
        }
        
        /// <comentarios/>
        public string PresentacionIntSKU {
            get {
                return this.presentacionIntSKUField;
            }
            set {
                this.presentacionIntSKUField = value;
            }
        }
        
        /// <comentarios/>
        public string PresentacionStrID {
            get {
                return this.presentacionStrIDField;
            }
            set {
                this.presentacionStrIDField = value;
            }
        }
        
        /// <comentarios/>
        public int TransaccionIntCantidad {
            get {
                return this.transaccionIntCantidadField;
            }
            set {
                this.transaccionIntCantidadField = value;
            }
        }
        
        /// <comentarios/>
        public string TransaccionStrTipoMov {
            get {
                return this.transaccionStrTipoMovField;
            }
            set {
                this.transaccionStrTipoMovField = value;
            }
        }
        
        /// <comentarios/>
        public string TransaccionStrSubTipoMov {
            get {
                return this.transaccionStrSubTipoMovField;
            }
            set {
                this.transaccionStrSubTipoMovField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TarjetasRegistradasCompletedEventHandler(object sender, TarjetasRegistradasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TarjetasRegistradasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TarjetasRegistradasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TarjetaCliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TarjetaCliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TarjetaClienteConfirmacionCompletedEventHandler(object sender, TarjetaClienteConfirmacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TarjetaClienteConfirmacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TarjetaClienteConfirmacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TarjetasRegistradasDemoCompletedEventHandler(object sender, TarjetasRegistradasDemoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TarjetasRegistradasDemoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TarjetasRegistradasDemoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TarjetaCliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TarjetaCliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TransaccionesCompletedEventHandler(object sender, TransaccionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransaccionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TransaccionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transacciones[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transacciones[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TransaccionesConfirmacionCompletedEventHandler(object sender, TransaccionesConfirmacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransaccionesConfirmacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TransaccionesConfirmacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TransaccionesDemoCompletedEventHandler(object sender, TransaccionesDemoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransaccionesDemoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TransaccionesDemoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Transacciones[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Transacciones[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MaestroCadenasCompletedEventHandler(object sender, MaestroCadenasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaestroCadenasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaestroCadenasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MaestroCadenasDemoCompletedEventHandler(object sender, MaestroCadenasDemoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaestroCadenasDemoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaestroCadenasDemoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MaestroTarjetasCompletedEventHandler(object sender, MaestroTarjetasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaestroTarjetasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaestroTarjetasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MaestroTarjetasDemoCompletedEventHandler(object sender, MaestroTarjetasDemoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaestroTarjetasDemoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaestroTarjetasDemoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MaestroSucursalesCompletedEventHandler(object sender, MaestroSucursalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaestroSucursalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaestroSucursalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MaestroSucursalesDemoCompletedEventHandler(object sender, MaestroSucursalesDemoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaestroSucursalesDemoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaestroSucursalesDemoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MaestroProductosCompletedEventHandler(object sender, MaestroProductosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaestroProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaestroProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MaestroProductosDemoCompletedEventHandler(object sender, MaestroProductosDemoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaestroProductosDemoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaestroProductosDemoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MaestroProductosPresentacionCompletedEventHandler(object sender, MaestroProductosPresentacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaestroProductosPresentacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaestroProductosPresentacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591