#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using EntitiesModel;

namespace EntitiesModel	
{
	public partial class pregunta
	{
		private long _id;
		public virtual long id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long _encuesta_id;
		public virtual long encuesta_id
		{
			get
			{
				return this._encuesta_id;
			}
			set
			{
				this._encuesta_id = value;
			}
		}
		
		private string _nombre;
		public virtual string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private int _orden;
		public virtual int orden
		{
			get
			{
				return this._orden;
			}
			set
			{
				this._orden = value;
			}
		}
		
		private string _explicacion;
		public virtual string explicacion
		{
			get
			{
				return this._explicacion;
			}
			set
			{
				this._explicacion = value;
			}
		}
		
		private string _despliegue;
		public virtual string despliegue
		{
			get
			{
				return this._despliegue;
			}
			set
			{
				this._despliegue = value;
			}
		}
		
		private DateTime? _fecha_inicial;
		public virtual DateTime? fecha_inicial
		{
			get
			{
				return this._fecha_inicial;
			}
			set
			{
				this._fecha_inicial = value;
			}
		}
		
		private DateTime? _fecha_final;
		public virtual DateTime? fecha_final
		{
			get
			{
				return this._fecha_final;
			}
			set
			{
				this._fecha_final = value;
			}
		}
		
		private DateTime? _fecha_alta;
		public virtual DateTime? fecha_alta
		{
			get
			{
				return this._fecha_alta;
			}
			set
			{
				this._fecha_alta = value;
			}
		}
		
		private DateTime? _fecha_cambio;
		public virtual DateTime? fecha_cambio
		{
			get
			{
				return this._fecha_cambio;
			}
			set
			{
				this._fecha_cambio = value;
			}
		}
		
		private DateTime? _fecha_baja;
		public virtual DateTime? fecha_baja
		{
			get
			{
				return this._fecha_baja;
			}
			set
			{
				this._fecha_baja = value;
			}
		}
		
		private Guid _usuario_alta_id;
		public virtual Guid usuario_alta_id
		{
			get
			{
				return this._usuario_alta_id;
			}
			set
			{
				this._usuario_alta_id = value;
			}
		}
		
		private Guid? _usuario_cambio_id;
		public virtual Guid? usuario_cambio_id
		{
			get
			{
				return this._usuario_cambio_id;
			}
			set
			{
				this._usuario_cambio_id = value;
			}
		}
		
		private Guid? _usuario_baja_id;
		public virtual Guid? usuario_baja_id
		{
			get
			{
				return this._usuario_baja_id;
			}
			set
			{
				this._usuario_baja_id = value;
			}
		}
		
		private encuesta _encuesta;
		public virtual encuesta encuesta
		{
			get
			{
				return this._encuesta;
			}
			set
			{
				this._encuesta = value;
			}
		}
		
		private IList<respuesta> _respuesta = new List<respuesta>();
		public virtual IList<respuesta> respuesta
		{
			get
			{
				return this._respuesta;
			}
		}
		
	}
}
#pragma warning restore 1591
