#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using EntitiesModel;

namespace EntitiesModel	
{
	public partial class distribuidor_direccion
	{
		private long _id;
		public virtual long id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long _distribuidor_id;
		public virtual long distribuidor_id
		{
			get
			{
				return this._distribuidor_id;
			}
			set
			{
				this._distribuidor_id = value;
			}
		}
		
		private string _lada;
		public virtual string lada
		{
			get
			{
				return this._lada;
			}
			set
			{
				this._lada = value;
			}
		}
		
		private string _telefono;
		public virtual string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				this._telefono = value;
			}
		}
		
		private string _correo_electronico;
		public virtual string correo_electronico
		{
			get
			{
				return this._correo_electronico;
			}
			set
			{
				this._correo_electronico = value;
			}
		}
		
		private string _calle;
		public virtual string calle
		{
			get
			{
				return this._calle;
			}
			set
			{
				this._calle = value;
			}
		}
		
		private string _entre_calle;
		public virtual string entre_calle
		{
			get
			{
				return this._entre_calle;
			}
			set
			{
				this._entre_calle = value;
			}
		}
		
		private string _y_calle;
		public virtual string y_calle
		{
			get
			{
				return this._y_calle;
			}
			set
			{
				this._y_calle = value;
			}
		}
		
		private string _colonia;
		public virtual string colonia
		{
			get
			{
				return this._colonia;
			}
			set
			{
				this._colonia = value;
			}
		}
		
		private string _numero;
		public virtual string numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		
		private string _municipio;
		public virtual string municipio
		{
			get
			{
				return this._municipio;
			}
			set
			{
				this._municipio = value;
			}
		}
		
		private string _estado;
		public virtual string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				this._estado = value;
			}
		}
		
		private string _codigo_postal;
		public virtual string codigo_postal
		{
			get
			{
				return this._codigo_postal;
			}
			set
			{
				this._codigo_postal = value;
			}
		}
		
		private DateTime _fecha_alta;
		public virtual DateTime fecha_alta
		{
			get
			{
				return this._fecha_alta;
			}
			set
			{
				this._fecha_alta = value;
			}
		}
		
		private DateTime? _fecha_cambio;
		public virtual DateTime? fecha_cambio
		{
			get
			{
				return this._fecha_cambio;
			}
			set
			{
				this._fecha_cambio = value;
			}
		}
		
		private DateTime? _fecha_baja;
		public virtual DateTime? fecha_baja
		{
			get
			{
				return this._fecha_baja;
			}
			set
			{
				this._fecha_baja = value;
			}
		}
		
		private Guid _usuario_alta_id;
		public virtual Guid usuario_alta_id
		{
			get
			{
				return this._usuario_alta_id;
			}
			set
			{
				this._usuario_alta_id = value;
			}
		}
		
		private Guid? _usuario_cambio_id;
		public virtual Guid? usuario_cambio_id
		{
			get
			{
				return this._usuario_cambio_id;
			}
			set
			{
				this._usuario_cambio_id = value;
			}
		}
		
		private Guid? _usuario_baja_id;
		public virtual Guid? usuario_baja_id
		{
			get
			{
				return this._usuario_baja_id;
			}
			set
			{
				this._usuario_baja_id = value;
			}
		}
		
		private string _zona;
		public virtual string zona
		{
			get
			{
				return this._zona;
			}
			set
			{
				this._zona = value;
			}
		}
		
		private string _gerente_regional;
		public virtual string gerente_regional
		{
			get
			{
				return this._gerente_regional;
			}
			set
			{
				this._gerente_regional = value;
			}
		}
		
		private distribuidor _distribuidor;
		public virtual distribuidor distribuidor
		{
			get
			{
				return this._distribuidor;
			}
			set
			{
				this._distribuidor = value;
			}
		}
		
	}
}
#pragma warning restore 1591
