#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using EntitiesModel;

namespace EntitiesModel	
{
	public partial class encuesta
	{
		private long _id;
		public virtual long id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long _tipo_encuesta_id;
		public virtual long tipo_encuesta_id
		{
			get
			{
				return this._tipo_encuesta_id;
			}
			set
			{
				this._tipo_encuesta_id = value;
			}
		}
		
		private string _nombre;
		public virtual string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private DateTime _fecha_inicial;
		public virtual DateTime fecha_inicial
		{
			get
			{
				return this._fecha_inicial;
			}
			set
			{
				this._fecha_inicial = value;
			}
		}
		
		private DateTime _fecha_final;
		public virtual DateTime fecha_final
		{
			get
			{
				return this._fecha_final;
			}
			set
			{
				this._fecha_final = value;
			}
		}
		
		private long _status_id;
		public virtual long status_id
		{
			get
			{
				return this._status_id;
			}
			set
			{
				this._status_id = value;
			}
		}
		
		private DateTime _fecha_status;
		public virtual DateTime fecha_status
		{
			get
			{
				return this._fecha_status;
			}
			set
			{
				this._fecha_status = value;
			}
		}
		
		private string _guion;
		public virtual string guion
		{
			get
			{
				return this._guion;
			}
			set
			{
				this._guion = value;
			}
		}
		
		private string _cierre;
		public virtual string cierre
		{
			get
			{
				return this._cierre;
			}
			set
			{
				this._cierre = value;
			}
		}
		
		private byte[] _logo;
		public virtual byte[] logo
		{
			get
			{
				return this._logo;
			}
			set
			{
				this._logo = value;
			}
		}
		
		private DateTime _fecha_alta;
		public virtual DateTime fecha_alta
		{
			get
			{
				return this._fecha_alta;
			}
			set
			{
				this._fecha_alta = value;
			}
		}
		
		private DateTime? _fecha_cambio;
		public virtual DateTime? fecha_cambio
		{
			get
			{
				return this._fecha_cambio;
			}
			set
			{
				this._fecha_cambio = value;
			}
		}
		
		private DateTime? _fecha_baja;
		public virtual DateTime? fecha_baja
		{
			get
			{
				return this._fecha_baja;
			}
			set
			{
				this._fecha_baja = value;
			}
		}
		
		private Guid _usuario_alta_id;
		public virtual Guid usuario_alta_id
		{
			get
			{
				return this._usuario_alta_id;
			}
			set
			{
				this._usuario_alta_id = value;
			}
		}
		
		private Guid? _usuario_cambio_id;
		public virtual Guid? usuario_cambio_id
		{
			get
			{
				return this._usuario_cambio_id;
			}
			set
			{
				this._usuario_cambio_id = value;
			}
		}
		
		private Guid? _usuario_baja_id;
		public virtual Guid? usuario_baja_id
		{
			get
			{
				return this._usuario_baja_id;
			}
			set
			{
				this._usuario_baja_id = value;
			}
		}
		
		private tipo_encuesta _tipo_encuesta;
		public virtual tipo_encuesta tipo_encuesta
		{
			get
			{
				return this._tipo_encuesta;
			}
			set
			{
				this._tipo_encuesta = value;
			}
		}
		
		private IList<pregunta> _pregunta = new List<pregunta>();
		public virtual IList<pregunta> pregunta
		{
			get
			{
				return this._pregunta;
			}
		}
		
	}
}
#pragma warning restore 1591
