#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using EntitiesModel;

namespace EntitiesModel	
{
	public partial class mecanica_detalle
	{
		private long _id;
		public virtual long id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long _mecanica_id;
		public virtual long mecanica_id
		{
			get
			{
				return this._mecanica_id;
			}
			set
			{
				this._mecanica_id = value;
			}
		}
		
		private long? _marca_id;
		public virtual long? marca_id
		{
			get
			{
				return this._marca_id;
			}
			set
			{
				this._marca_id = value;
			}
		}
		
		private long? _producto_id;
		public virtual long? producto_id
		{
			get
			{
				return this._producto_id;
			}
			set
			{
				this._producto_id = value;
			}
		}
		
		private producto _producto;
		public virtual producto producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				this._producto = value;
			}
		}
		
		private mecanica _mecanica;
		public virtual mecanica mecanica
		{
			get
			{
				return this._mecanica;
			}
			set
			{
				this._mecanica = value;
			}
		}
		
	}
}
#pragma warning restore 1591
