#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using EntitiesModel;

namespace EntitiesModel	
{
	public partial class participante
	{
		private long _id;
		public virtual long id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _clave;
		public virtual string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				this._clave = value;
			}
		}
		
		private string _nombre;
		public virtual string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				this._nombre = value;
			}
		}
		
		private string _apellido_paterno;
		public virtual string apellido_paterno
		{
			get
			{
				return this._apellido_paterno;
			}
			set
			{
				this._apellido_paterno = value;
			}
		}
		
		private string _apellido_materno;
		public virtual string apellido_materno
		{
			get
			{
				return this._apellido_materno;
			}
			set
			{
				this._apellido_materno = value;
			}
		}
		
		private string _razon_social;
		public virtual string razon_social
		{
			get
			{
				return this._razon_social;
			}
			set
			{
				this._razon_social = value;
			}
		}
		
		private string _documento_identidad;
		public virtual string documento_identidad
		{
			get
			{
				return this._documento_identidad;
			}
			set
			{
				this._documento_identidad = value;
			}
		}
		
		private string _correo_electronico;
		public virtual string correo_electronico
		{
			get
			{
				return this._correo_electronico;
			}
			set
			{
				this._correo_electronico = value;
			}
		}
		
		private long? _sexo_id;
		public virtual long? sexo_id
		{
			get
			{
				return this._sexo_id;
			}
			set
			{
				this._sexo_id = value;
			}
		}
		
		private long? _estado_civil_id;
		public virtual long? estado_civil_id
		{
			get
			{
				return this._estado_civil_id;
			}
			set
			{
				this._estado_civil_id = value;
			}
		}
		
		private DateTime? _fecha_nacimiento;
		public virtual DateTime? fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				this._fecha_nacimiento = value;
			}
		}
		
		private long? _distribuidor_id;
		public virtual long? distribuidor_id
		{
			get
			{
				return this._distribuidor_id;
			}
			set
			{
				this._distribuidor_id = value;
			}
		}
		
		private long? _tipo_participante_id;
		public virtual long? tipo_participante_id
		{
			get
			{
				return this._tipo_participante_id;
			}
			set
			{
				this._tipo_participante_id = value;
			}
		}
		
		private Guid? _usuario_alta;
		public virtual Guid? usuario_alta
		{
			get
			{
				return this._usuario_alta;
			}
			set
			{
				this._usuario_alta = value;
			}
		}
		
		private DateTime? _fecha_alta;
		public virtual DateTime? fecha_alta
		{
			get
			{
				return this._fecha_alta;
			}
			set
			{
				this._fecha_alta = value;
			}
		}
		
		private long? _status_participante_id;
		public virtual long? status_participante_id
		{
			get
			{
				return this._status_participante_id;
			}
			set
			{
				this._status_participante_id = value;
			}
		}
		
		private DateTime? _fecha_status;
		public virtual DateTime? fecha_status
		{
			get
			{
				return this._fecha_status;
			}
			set
			{
				this._fecha_status = value;
			}
		}
		
		private Guid? _usuario_status;
		public virtual Guid? usuario_status
		{
			get
			{
				return this._usuario_status;
			}
			set
			{
				this._usuario_status = value;
			}
		}
		
		private byte? _acepta_terminos;
		public virtual byte? acepta_terminos
		{
			get
			{
				return this._acepta_terminos;
			}
			set
			{
				this._acepta_terminos = value;
			}
		}
		
		private byte? _informacion_email;
		public virtual byte? informacion_email
		{
			get
			{
				return this._informacion_email;
			}
			set
			{
				this._informacion_email = value;
			}
		}
		
		private byte? _informacion_sms;
		public virtual byte? informacion_sms
		{
			get
			{
				return this._informacion_sms;
			}
			set
			{
				this._informacion_sms = value;
			}
		}
		
		private tipo_participante _tipo_participante;
		public virtual tipo_participante tipo_participante
		{
			get
			{
				return this._tipo_participante;
			}
			set
			{
				this._tipo_participante = value;
			}
		}
		
		private status_participante _status_participante;
		public virtual status_participante status_participante
		{
			get
			{
				return this._status_participante;
			}
			set
			{
				this._status_participante = value;
			}
		}
		
		private sexo _sexo;
		public virtual sexo sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				this._sexo = value;
			}
		}
		
		private distribuidor _distribuidor;
		public virtual distribuidor distribuidor
		{
			get
			{
				return this._distribuidor;
			}
			set
			{
				this._distribuidor = value;
			}
		}
		
		private IList<participante_distribuidor> _participante_distribuidor = new List<participante_distribuidor>();
		public virtual IList<participante_distribuidor> participante_distribuidor
		{
			get
			{
				return this._participante_distribuidor;
			}
		}
		
	}
}
#pragma warning restore 1591
