#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenterDB.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GaleniaTest")]
	public partial class CalendarioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcalendario(calendario instance);
    partial void Updatecalendario(calendario instance);
    partial void Deletecalendario(calendario instance);
    partial void Insertcalendario_canje(calendario_canje instance);
    partial void Updatecalendario_canje(calendario_canje instance);
    partial void Deletecalendario_canje(calendario_canje instance);
    #endregion
		
		public CalendarioDataContext() : 
				base(global::CallCenterDB.Properties.Settings.Default.GaleniaTestConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public CalendarioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CalendarioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CalendarioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CalendarioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<calendario> calendario
		{
			get
			{
				return this.GetTable<calendario>();
			}
		}
		
		public System.Data.Linq.Table<calendario_canje> calendario_canje
		{
			get
			{
				return this.GetTable<calendario_canje>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.calendario")]
	public partial class calendario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _descripcion;
		
		private string _descripcion_larga;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Ondescripcion_largaChanging(string value);
    partial void Ondescripcion_largaChanged();
    #endregion
		
		public calendario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_larga", DbType="VarChar(MAX)")]
		public string descripcion_larga
		{
			get
			{
				return this._descripcion_larga;
			}
			set
			{
				if ((this._descripcion_larga != value))
				{
					this.Ondescripcion_largaChanging(value);
					this.SendPropertyChanging();
					this._descripcion_larga = value;
					this.SendPropertyChanged("descripcion_larga");
					this.Ondescripcion_largaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.calendario_canje")]
	public partial class calendario_canje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private System.DateTime _fecha_inicial;
		
		private System.DateTime _fecha_final;
		
		private string _descripcion;
		
		private string _descripcion_larga;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void Onfecha_inicialChanging(System.DateTime value);
    partial void Onfecha_inicialChanged();
    partial void Onfecha_finalChanging(System.DateTime value);
    partial void Onfecha_finalChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Ondescripcion_largaChanging(string value);
    partial void Ondescripcion_largaChanged();
    #endregion
		
		public calendario_canje()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicial", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_inicial
		{
			get
			{
				return this._fecha_inicial;
			}
			set
			{
				if ((this._fecha_inicial != value))
				{
					this.Onfecha_inicialChanging(value);
					this.SendPropertyChanging();
					this._fecha_inicial = value;
					this.SendPropertyChanged("fecha_inicial");
					this.Onfecha_inicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_final", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_final
		{
			get
			{
				return this._fecha_final;
			}
			set
			{
				if ((this._fecha_final != value))
				{
					this.Onfecha_finalChanging(value);
					this.SendPropertyChanging();
					this._fecha_final = value;
					this.SendPropertyChanged("fecha_final");
					this.Onfecha_finalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_larga", DbType="NVarChar(MAX)")]
		public string descripcion_larga
		{
			get
			{
				return this._descripcion_larga;
			}
			set
			{
				if ((this._descripcion_larga != value))
				{
					this.Ondescripcion_largaChanging(value);
					this.SendPropertyChanging();
					this._descripcion_larga = value;
					this.SendPropertyChanged("descripcion_larga");
					this.Ondescripcion_largaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
