<?xml version="1.0" encoding="utf-8"?><Database Name="VipClubDB_stg" Class="CalendarioCODataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=184.106.188.43;Initial Catalog=VipClubDB_stg;Persist Security Info=True;User ID=sa" SettingsObjectName="CallCenterDB.Properties.Settings" SettingsPropertyName="VipClubDB_stgConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.calendario_co" Member="calendario_co">
    <Type Name="calendario_co">
      <Column Name="id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion_larga" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>