<?xml version="1.0" encoding="utf-8"?><Database Name="GaleniaTest" Class="Control_Acceso_PortalDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" 
              ConnectionString="Data Source=184.107.55.171;Initial Catalog=Galenia_Loyalty_Program;User ID=usr_galenia_lp;Password=galenialp@2015" 
              SettingsObjectName="CallCenterDB.Properties.Settings" SettingsPropertyName="GaleniaTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bitacora_accesos" Member="bitacora_accesos">
    <Type Name="bitacora_accesos">
      <Column Name="id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usuario_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="opcion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
</Database>