<%@ Page Title="" Language="C#" MasterPageFile="~/contenido.Master" AutoEventWireup="true" CodeBehind="mantenimientoCatalogos.aspx.cs" Inherits="ORMOperacion.mantenimientoCatalogos" %>

<%@ Register Assembly="Telerik.OpenAccess.Web.40, Version=2014.3.1027.1, Culture=neutral, PublicKeyToken=7ce17eeaf1d59342" Namespace="Telerik.OpenAccess.Web" TagPrefix="telerik" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head_contenido" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="body_contenido" runat="server">
    <div id="rounded-box4" >
 
            <telerik:OpenAccessLinqDataSource ID="OAFuenteTablas" EnableInsert="True"
                runat="server"
                EntityTypeName=""
                OnUpdating="OAFuenteTablas_Updating"
                OnInserting="OAFuenteTablas_Inserting" />
            <telerik:OpenAccessLinqDataSource ID="OACatalogosLealtad" runat="server"
                ContextTypeName="EntitiesModel.EntitiesModel" EntityTypeName=""
                ResourceSetName="catalogos_lealtads" OrderBy="Descripcion"  />
                <table width="100%">
                <tr>
                <td>
                <telerik:RadComboBox ID="rcbCatalogosLealtad" runat="server" AutoPostBack="True"
                Culture="es-MX" Height="200px"
                DataTextField="Descripcion_larga" DataValueField="Descripcion" EmptyMessage="Seleccione"
                OnSelectedIndexChanged="rcbCatalogosLealtad_SelectedIndexChanged"
                Style="margin-bottom: 0px" DataSourceID="OACatalogosLealtad">
                <Items>
                    <telerik:RadComboBoxItem runat="server" />
                </Items>
            </telerik:RadComboBox>
                </td>
                </tr>
                <tr>
                <td>
                   <div style="overflow: auto; width:1100px; height: 100%;">
                <telerik:RadGrid ID="gridResultados" runat="server" AllowAutomaticDeletes="True"
                    AllowAutomaticInserts="True" AllowAutomaticUpdates="True"
                    AllowCustomPaging="True" AllowSorting="True"
                    AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" CellSpacing="0"
                    Culture="es-MX" GridLines="None"
                    OnNeedDataSource="gridResultados_NeedDataSource"
                    OnInsertCommand="gridResultados_InsertCommand"
                    OnItemDataBound="gridResultados_ItemDataBound"
                    OnItemCommand="gridResultados_ItemCommand"
                    OnItemCreated="gridResultados_ItemCreated">
                    <MasterTableView CommandItemDisplay="TopAndBottom" AllowAutomaticInserts="true" EditMode="EditForms" OverrideDataSourceControlSorting="true">
                        <CommandItemSettings ExportToExcelText="Exportar a Excel"></CommandItemSettings>                        
                        <RowIndicatorColumn Visible="True" FilterControlAltText="Filter RowIndicator column">
                            <HeaderStyle Width="20px"></HeaderStyle>                            
                        </RowIndicatorColumn>
                        <ExpandCollapseColumn Visible="True" FilterControlAltText="Filter ExpandColumn column">
                            <HeaderStyle Width="20px"></HeaderStyle>
                        </ExpandCollapseColumn>
                        <EditFormSettings>
                            <EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
                        </EditFormSettings>
                    </MasterTableView>
                    <FilterMenu EnableImageSprites="False"></FilterMenu>
                </telerik:RadGrid>
            </div>
                </td>
                </tr>
                </table>
            
         
            <br />
    </div>
</asp:Content>
