<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="mantenimientocarrusel.aspx.cs" Inherits="ORMOperacion.mantenimientocarrusel"
    MasterPageFile="~/contenido.Master" %>

<%@ MasterType VirtualPath="~/contenido.Master" %>
<%@ Register Assembly="Telerik.OpenAccess.Web.40, Version=2014.3.1027.1, Culture=neutral, PublicKeyToken=7ce17eeaf1d59342" Namespace="Telerik.OpenAccess.Web" TagPrefix="telerik" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head_contenido" runat="server">
    <link id="styCalendario" runat="server" rel="stylesheet" type="text/css" />
    <style>
        .columnaurl {
            word-break: break-all;
        }

        .img_logo img {
            width: 140px !important;
            height: 100px !important;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="body_contenido" runat="server">
    <telerik:OpenAccessLinqDataSource ID="OACarrusel" runat="server"
        ContextTypeName="EntitiesModel.EntitiesModel" EntityTypeName="" EnableUpdate="true" EnableDelete="true" EnableInsert="true"
        ResourceSetName="programa_carrusels" OrderBy="id,orden" OnInserting="OACarrusel_Inserting" />

    <telerik:OpenAccessLinqDataSource ID="OAProgramas" runat="server"
        ContextTypeName="EntitiesModel.EntitiesModel" EntityTypeName="" EnableUpdate="true" EnableDelete="true" EnableInsert="true"
        ResourceSetName="programas" OrderBy="id" />


    <telerik:RadGrid runat="server" ID="rgCarrusel" DataSourceID="OACarrusel"
        MasterTableView-EditFormSettings-EditColumn-InsertText="Insertar"
        MasterTableView-EditFormSettings-EditColumn-EditText="Editar"
        MasterTableView-EditFormSettings-EditColumn-UpdateText="Actualizar"
        MasterTableView-EditFormSettings-EditColumn-CancelText="Cancelar"
        MasterTableView-CommandItemSettings-RefreshText="Refrescar"
        AutoGenerateEditColumn="true" AutoGenerateColumns="false" AutoGenerateDeleteColumn="true"
        AllowAutomaticUpdates="true" AllowAutomaticInserts="true" AllowAutomaticDeletes="true"
        OnInsertCommand="rgCarrusel_InsertCommand">
        <MasterTableView DataKeyNames="id" CommandItemDisplay="TopAndBottom">
            <Columns>
                <telerik:GridTemplateColumn HeaderText="Programa" DataField="programa_id" UniqueName="programa_id">
                    <ItemTemplate>
                        <asp:Label runat="server" Text='<%# Eval("programa.descripcion") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <telerik:RadComboBox runat="server" ID="rcbPrograma" DataSourceID="OAProgramas" DataValueField="id" DataTextField="descripcion_larga">
                            <DefaultItem Text="Seleccionar un programa" Value="0" />
                        </telerik:RadComboBox>
                    </EditItemTemplate>
                </telerik:GridTemplateColumn>
                <telerik:GridBoundColumn UniqueName="orden" DataField="orden" HeaderText="Orden"></telerik:GridBoundColumn>
                <telerik:GridBinaryImageColumn UniqueName="imagen_carrusel" DataField="imagen_carrusel" HeaderText="Imagen" ItemStyle-CssClass="img_logo"></telerik:GridBinaryImageColumn>
                <telerik:GridBoundColumn UniqueName="url_imagen" DataField="url_imagen" HeaderText="URL Imagen"></telerik:GridBoundColumn>
                <telerik:GridBoundColumn UniqueName="descripcion" DataField="descripcion" HeaderText="Descripcion"></telerik:GridBoundColumn>
                <telerik:GridDateTimeColumn UniqueName="fecha_inicio_vigencia" DataField="fecha_inicio_vigencia" HeaderText="fecha_inicio_vigencia"></telerik:GridDateTimeColumn>
                <telerik:GridDateTimeColumn UniqueName="fecha_fin_vigencia" DataField="fecha_fin_vigencia" HeaderText="fecha_fin_vigencia"></telerik:GridDateTimeColumn>
            </Columns>
        </MasterTableView>
    </telerik:RadGrid>
</asp:Content>
