<?xml version="1.0" encoding="utf-8"?><Database Name="VipClubDB_stg" Class="Tablas_brDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=184.106.188.43;Initial Catalog=VipClubDB_stg;User ID=sa" SettingsObjectName="CallCenterDB.Properties.Settings" SettingsPropertyName="VipClubDB_stgConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.distributor" Member="distributor">
    <Type Name="distributor">
      <Column Name="id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="clave" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion_larga" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="country_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="usuario_alta_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="usuario_cambio_id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="usuario_baja_id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="fecha_alta" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fecha_cambio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fecha_baja" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="url_imagen" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.participante" Member="participante">
    <Type Name="participante">
      <Column Name="id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="clave_participante" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellido_paterno" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="apellido_materno" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="status_participante_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="sexo_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="tipo_participante_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="correo_electronico" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="estado_civil_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha_nacimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="distributor_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha_status" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fecha_alta" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fecha_cambio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="participante_participante" Member="participante2" ThisKey="id" OtherKey="id" Type="participante" Cardinality="One" />
      <Association Name="participante_participante1" Member="participante4" ThisKey="id" OtherKey="id" Type="participante" Cardinality="One" />
      <Association Name="participante_participante" Member="participante1" ThisKey="id" OtherKey="id" Type="participante" IsForeignKey="true" />
      <Association Name="participante_participante1" Member="participante3" ThisKey="id" OtherKey="id" Type="participante" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.distributors_tipo_br" Member="distributors_tipo_br">
    <Type Name="distributors_tipo_br">
      <Column Name="id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="distributor_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="tipo_distributor_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="usuario_alta_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="usuario_cambio_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="usuario_baja_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha_alta" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fecha_cambio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fecha_baja" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="country_code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tipo_distributor_br" Member="tipo_distributor_br">
    <Type Name="tipo_distributor_br">
      <Column Name="id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="clave" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion_larga" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="usuario_alta_id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="usuario_cambio_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="usuario_baja_id" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha_alta" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fecha_cambio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fecha_baja" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="country_code" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </Type>
  </Table>
</Database>