#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenterDB.Linq.br
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using System.Configuration;


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "GaleniaTest")]
	public partial class Tablas_brDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertdistributor(distributor instance);
    partial void Updatedistributor(distributor instance);
    partial void Deletedistributor(distributor instance);
    partial void Insertparticipante(participante instance);
    partial void Updateparticipante(participante instance);
    partial void Deleteparticipante(participante instance);
    partial void Insertdistributors_tipo_br(distributors_tipo_br instance);
    partial void Updatedistributors_tipo_br(distributors_tipo_br instance);
    partial void Deletedistributors_tipo_br(distributors_tipo_br instance);
    partial void Inserttipo_distributor_br(tipo_distributor_br instance);
    partial void Updatetipo_distributor_br(tipo_distributor_br instance);
    partial void Deletetipo_distributor_br(tipo_distributor_br instance);
    #endregion
		
		public Tablas_brDataContext() :
        base(ConfigurationManager.ConnectionStrings["GaleniaTest"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Tablas_brDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Tablas_brDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Tablas_brDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Tablas_brDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<distributor> distributor
		{
			get
			{
				return this.GetTable<distributor>();
			}
		}
		
		public System.Data.Linq.Table<participante> participante
		{
			get
			{
				return this.GetTable<participante>();
			}
		}
		
		public System.Data.Linq.Table<distributors_tipo_br> distributors_tipo_br
		{
			get
			{
				return this.GetTable<distributors_tipo_br>();
			}
		}
		
		public System.Data.Linq.Table<tipo_distributor_br> tipo_distributor_br
		{
			get
			{
				return this.GetTable<tipo_distributor_br>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.distributor")]
	public partial class distributor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private string _clave;
		
		private string _descripcion;
		
		private string _descripcion_larga;
		
		private decimal _country_id;
		
		private System.Guid _usuario_alta_id;
		
		private System.Nullable<System.Guid> _usuario_cambio_id;
		
		private System.Nullable<System.Guid> _usuario_baja_id;
		
		private System.DateTime _fecha_alta;
		
		private System.Nullable<System.DateTime> _fecha_cambio;
		
		private System.Nullable<System.DateTime> _fecha_baja;
		
		private string _url_imagen;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Ondescripcion_largaChanging(string value);
    partial void Ondescripcion_largaChanged();
    partial void Oncountry_idChanging(decimal value);
    partial void Oncountry_idChanged();
    partial void Onusuario_alta_idChanging(System.Guid value);
    partial void Onusuario_alta_idChanged();
    partial void Onusuario_cambio_idChanging(System.Nullable<System.Guid> value);
    partial void Onusuario_cambio_idChanged();
    partial void Onusuario_baja_idChanging(System.Nullable<System.Guid> value);
    partial void Onusuario_baja_idChanged();
    partial void Onfecha_altaChanging(System.DateTime value);
    partial void Onfecha_altaChanged();
    partial void Onfecha_cambioChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_cambioChanged();
    partial void Onfecha_bajaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_bajaChanged();
    partial void Onurl_imagenChanging(string value);
    partial void Onurl_imagenChanged();
    #endregion
		
		public distributor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_larga", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descripcion_larga
		{
			get
			{
				return this._descripcion_larga;
			}
			set
			{
				if ((this._descripcion_larga != value))
				{
					this.Ondescripcion_largaChanging(value);
					this.SendPropertyChanging();
					this._descripcion_larga = value;
					this.SendPropertyChanged("descripcion_larga");
					this.Ondescripcion_largaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_id", DbType="Decimal(18,0) NOT NULL")]
		public decimal country_id
		{
			get
			{
				return this._country_id;
			}
			set
			{
				if ((this._country_id != value))
				{
					this.Oncountry_idChanging(value);
					this.SendPropertyChanging();
					this._country_id = value;
					this.SendPropertyChanged("country_id");
					this.Oncountry_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_alta_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid usuario_alta_id
		{
			get
			{
				return this._usuario_alta_id;
			}
			set
			{
				if ((this._usuario_alta_id != value))
				{
					this.Onusuario_alta_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_alta_id = value;
					this.SendPropertyChanged("usuario_alta_id");
					this.Onusuario_alta_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_cambio_id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> usuario_cambio_id
		{
			get
			{
				return this._usuario_cambio_id;
			}
			set
			{
				if ((this._usuario_cambio_id != value))
				{
					this.Onusuario_cambio_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_cambio_id = value;
					this.SendPropertyChanged("usuario_cambio_id");
					this.Onusuario_cambio_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_baja_id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> usuario_baja_id
		{
			get
			{
				return this._usuario_baja_id;
			}
			set
			{
				if ((this._usuario_baja_id != value))
				{
					this.Onusuario_baja_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_baja_id = value;
					this.SendPropertyChanged("usuario_baja_id");
					this.Onusuario_baja_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_alta", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_alta
		{
			get
			{
				return this._fecha_alta;
			}
			set
			{
				if ((this._fecha_alta != value))
				{
					this.Onfecha_altaChanging(value);
					this.SendPropertyChanging();
					this._fecha_alta = value;
					this.SendPropertyChanged("fecha_alta");
					this.Onfecha_altaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_cambio", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_cambio
		{
			get
			{
				return this._fecha_cambio;
			}
			set
			{
				if ((this._fecha_cambio != value))
				{
					this.Onfecha_cambioChanging(value);
					this.SendPropertyChanging();
					this._fecha_cambio = value;
					this.SendPropertyChanged("fecha_cambio");
					this.Onfecha_cambioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_baja", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_baja
		{
			get
			{
				return this._fecha_baja;
			}
			set
			{
				if ((this._fecha_baja != value))
				{
					this.Onfecha_bajaChanging(value);
					this.SendPropertyChanging();
					this._fecha_baja = value;
					this.SendPropertyChanged("fecha_baja");
					this.Onfecha_bajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url_imagen", DbType="VarChar(250)")]
		public string url_imagen
		{
			get
			{
				return this._url_imagen;
			}
			set
			{
				if ((this._url_imagen != value))
				{
					this.Onurl_imagenChanging(value);
					this.SendPropertyChanging();
					this._url_imagen = value;
					this.SendPropertyChanged("url_imagen");
					this.Onurl_imagenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.participante")]
	public partial class participante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private string _clave_participante;
		
		private string _nombre;
		
		private string _apellido_paterno;
		
		private string _apellido_materno;
		
		private decimal _status_participante_id;
		
		private System.Nullable<decimal> _sexo_id;
		
		private System.Nullable<decimal> _tipo_participante_id;
		
		private string _correo_electronico;
		
		private System.Nullable<decimal> _estado_civil_id;
		
		private System.Nullable<System.DateTime> _fecha_nacimiento;
		
		private System.Nullable<decimal> _distributor_id;
		
		private System.DateTime _fecha_status;
		
		private System.DateTime _fecha_alta;
		
		private System.Nullable<System.DateTime> _fecha_cambio;
		
		private EntityRef<participante> _participante2;
		
		private EntityRef<participante> _participante4;
		
		private EntityRef<participante> _participante1;
		
		private EntityRef<participante> _participante3;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void Onclave_participanteChanging(string value);
    partial void Onclave_participanteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onapellido_paternoChanging(string value);
    partial void Onapellido_paternoChanged();
    partial void Onapellido_maternoChanging(string value);
    partial void Onapellido_maternoChanged();
    partial void Onstatus_participante_idChanging(decimal value);
    partial void Onstatus_participante_idChanged();
    partial void Onsexo_idChanging(System.Nullable<decimal> value);
    partial void Onsexo_idChanged();
    partial void Ontipo_participante_idChanging(System.Nullable<decimal> value);
    partial void Ontipo_participante_idChanged();
    partial void Oncorreo_electronicoChanging(string value);
    partial void Oncorreo_electronicoChanged();
    partial void Onestado_civil_idChanging(System.Nullable<decimal> value);
    partial void Onestado_civil_idChanged();
    partial void Onfecha_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_nacimientoChanged();
    partial void Ondistributor_idChanging(System.Nullable<decimal> value);
    partial void Ondistributor_idChanged();
    partial void Onfecha_statusChanging(System.DateTime value);
    partial void Onfecha_statusChanged();
    partial void Onfecha_altaChanging(System.DateTime value);
    partial void Onfecha_altaChanged();
    partial void Onfecha_cambioChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_cambioChanged();
    #endregion
		
		public participante()
		{
			this._participante2 = default(EntityRef<participante>);
			this._participante4 = default(EntityRef<participante>);
			this._participante1 = default(EntityRef<participante>);
			this._participante3 = default(EntityRef<participante>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					if ((this._participante1.HasLoadedOrAssignedValue || this._participante3.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave_participante", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string clave_participante
		{
			get
			{
				return this._clave_participante;
			}
			set
			{
				if ((this._clave_participante != value))
				{
					this.Onclave_participanteChanging(value);
					this.SendPropertyChanging();
					this._clave_participante = value;
					this.SendPropertyChanged("clave_participante");
					this.Onclave_participanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_paterno", DbType="VarChar(50)")]
		public string apellido_paterno
		{
			get
			{
				return this._apellido_paterno;
			}
			set
			{
				if ((this._apellido_paterno != value))
				{
					this.Onapellido_paternoChanging(value);
					this.SendPropertyChanging();
					this._apellido_paterno = value;
					this.SendPropertyChanged("apellido_paterno");
					this.Onapellido_paternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_materno", DbType="VarChar(50)")]
		public string apellido_materno
		{
			get
			{
				return this._apellido_materno;
			}
			set
			{
				if ((this._apellido_materno != value))
				{
					this.Onapellido_maternoChanging(value);
					this.SendPropertyChanging();
					this._apellido_materno = value;
					this.SendPropertyChanged("apellido_materno");
					this.Onapellido_maternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_participante_id", DbType="Decimal(18,0) NOT NULL")]
		public decimal status_participante_id
		{
			get
			{
				return this._status_participante_id;
			}
			set
			{
				if ((this._status_participante_id != value))
				{
					this.Onstatus_participante_idChanging(value);
					this.SendPropertyChanging();
					this._status_participante_id = value;
					this.SendPropertyChanged("status_participante_id");
					this.Onstatus_participante_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo_id", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> sexo_id
		{
			get
			{
				return this._sexo_id;
			}
			set
			{
				if ((this._sexo_id != value))
				{
					this.Onsexo_idChanging(value);
					this.SendPropertyChanging();
					this._sexo_id = value;
					this.SendPropertyChanged("sexo_id");
					this.Onsexo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_participante_id", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> tipo_participante_id
		{
			get
			{
				return this._tipo_participante_id;
			}
			set
			{
				if ((this._tipo_participante_id != value))
				{
					this.Ontipo_participante_idChanging(value);
					this.SendPropertyChanging();
					this._tipo_participante_id = value;
					this.SendPropertyChanged("tipo_participante_id");
					this.Ontipo_participante_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_electronico", DbType="VarChar(80)")]
		public string correo_electronico
		{
			get
			{
				return this._correo_electronico;
			}
			set
			{
				if ((this._correo_electronico != value))
				{
					this.Oncorreo_electronicoChanging(value);
					this.SendPropertyChanging();
					this._correo_electronico = value;
					this.SendPropertyChanged("correo_electronico");
					this.Oncorreo_electronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_civil_id", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> estado_civil_id
		{
			get
			{
				return this._estado_civil_id;
			}
			set
			{
				if ((this._estado_civil_id != value))
				{
					this.Onestado_civil_idChanging(value);
					this.SendPropertyChanging();
					this._estado_civil_id = value;
					this.SendPropertyChanged("estado_civil_id");
					this.Onestado_civil_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distributor_id", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> distributor_id
		{
			get
			{
				return this._distributor_id;
			}
			set
			{
				if ((this._distributor_id != value))
				{
					this.Ondistributor_idChanging(value);
					this.SendPropertyChanging();
					this._distributor_id = value;
					this.SendPropertyChanged("distributor_id");
					this.Ondistributor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_status", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_status
		{
			get
			{
				return this._fecha_status;
			}
			set
			{
				if ((this._fecha_status != value))
				{
					this.Onfecha_statusChanging(value);
					this.SendPropertyChanging();
					this._fecha_status = value;
					this.SendPropertyChanged("fecha_status");
					this.Onfecha_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_alta", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_alta
		{
			get
			{
				return this._fecha_alta;
			}
			set
			{
				if ((this._fecha_alta != value))
				{
					this.Onfecha_altaChanging(value);
					this.SendPropertyChanging();
					this._fecha_alta = value;
					this.SendPropertyChanged("fecha_alta");
					this.Onfecha_altaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_cambio", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_cambio
		{
			get
			{
				return this._fecha_cambio;
			}
			set
			{
				if ((this._fecha_cambio != value))
				{
					this.Onfecha_cambioChanging(value);
					this.SendPropertyChanging();
					this._fecha_cambio = value;
					this.SendPropertyChanged("fecha_cambio");
					this.Onfecha_cambioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="participante_participante", Storage="_participante2", ThisKey="id", OtherKey="id", IsUnique=true, IsForeignKey=false)]
		public participante participante2
		{
			get
			{
				return this._participante2.Entity;
			}
			set
			{
				participante previousValue = this._participante2.Entity;
				if (((previousValue != value) 
							|| (this._participante2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._participante2.Entity = null;
						previousValue.participante1 = null;
					}
					this._participante2.Entity = value;
					if ((value != null))
					{
						value.participante1 = this;
					}
					this.SendPropertyChanged("participante2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="participante_participante1", Storage="_participante4", ThisKey="id", OtherKey="id", IsUnique=true, IsForeignKey=false)]
		public participante participante4
		{
			get
			{
				return this._participante4.Entity;
			}
			set
			{
				participante previousValue = this._participante4.Entity;
				if (((previousValue != value) 
							|| (this._participante4.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._participante4.Entity = null;
						previousValue.participante3 = null;
					}
					this._participante4.Entity = value;
					if ((value != null))
					{
						value.participante3 = this;
					}
					this.SendPropertyChanged("participante4");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="participante_participante", Storage="_participante1", ThisKey="id", OtherKey="id", IsForeignKey=true)]
		public participante participante1
		{
			get
			{
				return this._participante1.Entity;
			}
			set
			{
				participante previousValue = this._participante1.Entity;
				if (((previousValue != value) 
							|| (this._participante1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._participante1.Entity = null;
						previousValue.participante2 = null;
					}
					this._participante1.Entity = value;
					if ((value != null))
					{
						value.participante2 = this;
						this._id = value.id;
					}
					else
					{
						this._id = default(decimal);
					}
					this.SendPropertyChanged("participante1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="participante_participante1", Storage="_participante3", ThisKey="id", OtherKey="id", IsForeignKey=true)]
		public participante participante3
		{
			get
			{
				return this._participante3.Entity;
			}
			set
			{
				participante previousValue = this._participante3.Entity;
				if (((previousValue != value) 
							|| (this._participante3.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._participante3.Entity = null;
						previousValue.participante4 = null;
					}
					this._participante3.Entity = value;
					if ((value != null))
					{
						value.participante4 = this;
						this._id = value.id;
					}
					else
					{
						this._id = default(decimal);
					}
					this.SendPropertyChanged("participante3");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.distributors_tipo_br")]
	public partial class distributors_tipo_br : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private decimal _distributor_id;
		
		private decimal _tipo_distributor_id;
		
		private decimal _usuario_alta_id;
		
		private System.Nullable<decimal> _usuario_cambio_id;
		
		private System.Nullable<decimal> _usuario_baja_id;
		
		private System.DateTime _fecha_alta;
		
		private System.Nullable<System.DateTime> _fecha_cambio;
		
		private System.Nullable<System.DateTime> _fecha_baja;
		
		private string _country_code;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void Ondistributor_idChanging(decimal value);
    partial void Ondistributor_idChanged();
    partial void Ontipo_distributor_idChanging(decimal value);
    partial void Ontipo_distributor_idChanged();
    partial void Onusuario_alta_idChanging(decimal value);
    partial void Onusuario_alta_idChanged();
    partial void Onusuario_cambio_idChanging(System.Nullable<decimal> value);
    partial void Onusuario_cambio_idChanged();
    partial void Onusuario_baja_idChanging(System.Nullable<decimal> value);
    partial void Onusuario_baja_idChanged();
    partial void Onfecha_altaChanging(System.DateTime value);
    partial void Onfecha_altaChanged();
    partial void Onfecha_cambioChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_cambioChanged();
    partial void Onfecha_bajaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_bajaChanged();
    partial void Oncountry_codeChanging(string value);
    partial void Oncountry_codeChanged();
    #endregion
		
		public distributors_tipo_br()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distributor_id", DbType="Decimal(18,0) NOT NULL")]
		public decimal distributor_id
		{
			get
			{
				return this._distributor_id;
			}
			set
			{
				if ((this._distributor_id != value))
				{
					this.Ondistributor_idChanging(value);
					this.SendPropertyChanging();
					this._distributor_id = value;
					this.SendPropertyChanged("distributor_id");
					this.Ondistributor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_distributor_id", DbType="Decimal(18,0) NOT NULL")]
		public decimal tipo_distributor_id
		{
			get
			{
				return this._tipo_distributor_id;
			}
			set
			{
				if ((this._tipo_distributor_id != value))
				{
					this.Ontipo_distributor_idChanging(value);
					this.SendPropertyChanging();
					this._tipo_distributor_id = value;
					this.SendPropertyChanged("tipo_distributor_id");
					this.Ontipo_distributor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_alta_id", DbType="Decimal(18,0) NOT NULL")]
		public decimal usuario_alta_id
		{
			get
			{
				return this._usuario_alta_id;
			}
			set
			{
				if ((this._usuario_alta_id != value))
				{
					this.Onusuario_alta_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_alta_id = value;
					this.SendPropertyChanged("usuario_alta_id");
					this.Onusuario_alta_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_cambio_id", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> usuario_cambio_id
		{
			get
			{
				return this._usuario_cambio_id;
			}
			set
			{
				if ((this._usuario_cambio_id != value))
				{
					this.Onusuario_cambio_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_cambio_id = value;
					this.SendPropertyChanged("usuario_cambio_id");
					this.Onusuario_cambio_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_baja_id", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> usuario_baja_id
		{
			get
			{
				return this._usuario_baja_id;
			}
			set
			{
				if ((this._usuario_baja_id != value))
				{
					this.Onusuario_baja_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_baja_id = value;
					this.SendPropertyChanged("usuario_baja_id");
					this.Onusuario_baja_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_alta", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_alta
		{
			get
			{
				return this._fecha_alta;
			}
			set
			{
				if ((this._fecha_alta != value))
				{
					this.Onfecha_altaChanging(value);
					this.SendPropertyChanging();
					this._fecha_alta = value;
					this.SendPropertyChanged("fecha_alta");
					this.Onfecha_altaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_cambio", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_cambio
		{
			get
			{
				return this._fecha_cambio;
			}
			set
			{
				if ((this._fecha_cambio != value))
				{
					this.Onfecha_cambioChanging(value);
					this.SendPropertyChanging();
					this._fecha_cambio = value;
					this.SendPropertyChanged("fecha_cambio");
					this.Onfecha_cambioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_baja", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_baja
		{
			get
			{
				return this._fecha_baja;
			}
			set
			{
				if ((this._fecha_baja != value))
				{
					this.Onfecha_bajaChanging(value);
					this.SendPropertyChanging();
					this._fecha_baja = value;
					this.SendPropertyChanged("fecha_baja");
					this.Onfecha_bajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_code", DbType="VarChar(50)")]
		public string country_code
		{
			get
			{
				return this._country_code;
			}
			set
			{
				if ((this._country_code != value))
				{
					this.Oncountry_codeChanging(value);
					this.SendPropertyChanging();
					this._country_code = value;
					this.SendPropertyChanged("country_code");
					this.Oncountry_codeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tipo_distributor_br")]
	public partial class tipo_distributor_br : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private string _clave;
		
		private string _descripcion;
		
		private string _descripcion_larga;
		
		private decimal _usuario_alta_id;
		
		private System.Nullable<decimal> _usuario_cambio_id;
		
		private System.Nullable<decimal> _usuario_baja_id;
		
		private System.DateTime _fecha_alta;
		
		private System.Nullable<System.DateTime> _fecha_cambio;
		
		private System.Nullable<System.DateTime> _fecha_baja;
		
		private string _country_code;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Ondescripcion_largaChanging(string value);
    partial void Ondescripcion_largaChanged();
    partial void Onusuario_alta_idChanging(decimal value);
    partial void Onusuario_alta_idChanged();
    partial void Onusuario_cambio_idChanging(System.Nullable<decimal> value);
    partial void Onusuario_cambio_idChanged();
    partial void Onusuario_baja_idChanging(System.Nullable<decimal> value);
    partial void Onusuario_baja_idChanged();
    partial void Onfecha_altaChanging(System.DateTime value);
    partial void Onfecha_altaChanged();
    partial void Onfecha_cambioChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_cambioChanged();
    partial void Onfecha_bajaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_bajaChanged();
    partial void Oncountry_codeChanging(string value);
    partial void Oncountry_codeChanged();
    #endregion
		
		public tipo_distributor_br()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_larga", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string descripcion_larga
		{
			get
			{
				return this._descripcion_larga;
			}
			set
			{
				if ((this._descripcion_larga != value))
				{
					this.Ondescripcion_largaChanging(value);
					this.SendPropertyChanging();
					this._descripcion_larga = value;
					this.SendPropertyChanged("descripcion_larga");
					this.Ondescripcion_largaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_alta_id", DbType="Decimal(18,0) NOT NULL")]
		public decimal usuario_alta_id
		{
			get
			{
				return this._usuario_alta_id;
			}
			set
			{
				if ((this._usuario_alta_id != value))
				{
					this.Onusuario_alta_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_alta_id = value;
					this.SendPropertyChanged("usuario_alta_id");
					this.Onusuario_alta_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_cambio_id", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> usuario_cambio_id
		{
			get
			{
				return this._usuario_cambio_id;
			}
			set
			{
				if ((this._usuario_cambio_id != value))
				{
					this.Onusuario_cambio_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_cambio_id = value;
					this.SendPropertyChanged("usuario_cambio_id");
					this.Onusuario_cambio_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_baja_id", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> usuario_baja_id
		{
			get
			{
				return this._usuario_baja_id;
			}
			set
			{
				if ((this._usuario_baja_id != value))
				{
					this.Onusuario_baja_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_baja_id = value;
					this.SendPropertyChanged("usuario_baja_id");
					this.Onusuario_baja_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_alta", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_alta
		{
			get
			{
				return this._fecha_alta;
			}
			set
			{
				if ((this._fecha_alta != value))
				{
					this.Onfecha_altaChanging(value);
					this.SendPropertyChanging();
					this._fecha_alta = value;
					this.SendPropertyChanged("fecha_alta");
					this.Onfecha_altaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_cambio", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_cambio
		{
			get
			{
				return this._fecha_cambio;
			}
			set
			{
				if ((this._fecha_cambio != value))
				{
					this.Onfecha_cambioChanging(value);
					this.SendPropertyChanging();
					this._fecha_cambio = value;
					this.SendPropertyChanged("fecha_cambio");
					this.Onfecha_cambioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_baja", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_baja
		{
			get
			{
				return this._fecha_baja;
			}
			set
			{
				if ((this._fecha_baja != value))
				{
					this.Onfecha_bajaChanging(value);
					this.SendPropertyChanging();
					this._fecha_baja = value;
					this.SendPropertyChanged("fecha_baja");
					this.Onfecha_bajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_code", DbType="VarChar(5)")]
		public string country_code
		{
			get
			{
				return this._country_code;
			}
			set
			{
				if ((this._country_code != value))
				{
					this.Oncountry_codeChanging(value);
					this.SendPropertyChanging();
					this._country_code = value;
					this.SendPropertyChanged("country_code");
					this.Oncountry_codeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
